CREATE TABLE EMPLOYEES 
(	EMPLOYEE_ID NUMBER(6,0), 
FIRST_NAME VARCHAR2(20 BYTE), 
LAST_NAME VARCHAR2(25 BYTE) CONSTRAINT EMP_LAST_NAME_NN NOT NULL, 
EMAIL VARCHAR2(25 BYTE) CONSTRAINT EMP_EMAIL_NN NOT NULL, 
PHONE_NUMBER VARCHAR2(20 BYTE), 
HIRE_DATE DATE CONSTRAINT EMP_HIRE_DATE_NN NOT NULL, 
JOB_ID VARCHAR2(10 BYTE) CONSTRAINT EMP_JOB_NN NOT NULL, 
SALARY NUMBER(8,2), 
COMMISSION_PCT NUMBER(2,2), 
MANAGER_ID NUMBER(6,0), 
DEPARTMENT_ID NUMBER(4,0), 

 CONSTRAINT EMP_SALARY_MIN CHECK (salary > 0), 
 CONSTRAINT EMP_EMAIL_UK UNIQUE (EMAIL)
 CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY (EMPLOYEE_ID)
 CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
  REFERENCES DEPARTMENTS (DEPARTMENT_ID), 
 CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID)
  REFERENCES JOBS (JOB_ID), 
 CONSTRAINT EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID)
  REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

CREATE TABLE DEPARTMENTS 
(	DEPARTMENT_ID NUMBER(4,0), 
DEPARTMENT_NAME VARCHAR2(30 BYTE) CONSTRAINT DEPT_NAME_NN NOT NULL, 
MANAGER_ID NUMBER(6,0), 
LOCATION_ID NUMBER(4,0), 
 CONSTRAINT DEPT_ID_PK PRIMARY KEY (DEPARTMENT_ID)
 CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID)
  REFERENCES LOCATIONS (LOCATION_ID), 
 CONSTRAINT DEPT_MGR_FK FOREIGN KEY (MANAGER_ID)
  REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

CREATE TABLE LOCATIONS 
(	LOCATION_ID NUMBER(4,0), 
STREET_ADDRESS VARCHAR2(40 BYTE), 
POSTAL_CODE VARCHAR2(12 BYTE), 
CITY VARCHAR2(30 BYTE) CONSTRAINT LOC_CITY_NN NOT NULL, 
STATE_PROVINCE VARCHAR2(25 BYTE), 
COUNTRY_ID CHAR(2 BYTE), 
 CONSTRAINT LOC_ID_PK PRIMARY KEY (LOCATION_ID)
 CONSTRAINT LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID)
  REFERENCES COUNTRIES (COUNTRY_ID)
);

CREATE TABLE COUNTRIES 
(	COUNTRY_ID CHAR(2 BYTE) CONSTRAINT COUNTRY_ID_NN NOT NULL, 
COUNTRY_NAME VARCHAR2(40 BYTE), 
REGION_ID NUMBER, 
 CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID), 
 CONSTRAINT COUNTR_REG_FK FOREIGN KEY (REGION_ID)
  REFERENCES REGIONS (REGION_ID)
);

 CREATE TABLE REGIONS 
(	REGION_ID NUMBER CONSTRAINT REGION_ID_NN NOT NULL, 
REGION_NAME VARCHAR2(25 BYTE), 
 CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID)
);

CREATE TABLE JOBS 
(	JOB_ID VARCHAR2(10 BYTE), 
JOB_TITLE VARCHAR2(35 BYTE) CONSTRAINT JOB_TITLE_NN NOT NULL, 
MIN_SALARY NUMBER(6,0), 
MAX_SALARY NUMBER(6,0), 
 CONSTRAINT JOB_ID_PK PRIMARY KEY (JOB_ID)
);
  
CREATE TABLE JOB_HISTORY 
(	EMPLOYEE_ID NUMBER(6,0) CONSTRAINT JHIST_EMPLOYEE_NN NOT NULL, 
START_DATE DATE CONSTRAINT JHIST_START_DATE_NN NOT NULL, 
END_DATE DATE CONSTRAINT JHIST_END_DATE_NN NOT NULL, 
JOB_ID VARCHAR2(10 BYTE) CONSTRAINT JHIST_JOB_NN NOT NULL, 
DEPARTMENT_ID NUMBER(4,0), 
 CONSTRAINT JHIST_DATE_INTERVAL CHECK (end_date > start_date), 
 CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY (EMPLOYEE_ID, START_DATE)

 CONSTRAINT JHIST_JOB_FK FOREIGN KEY (JOB_ID)
  REFERENCES JOBS (JOB_ID), 
 CONSTRAINT JHIST_EMP_FK FOREIGN KEY (EMPLOYEE_ID)
  REFERENCES EMPLOYEES (EMPLOYEE_ID), 
 CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
  REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);

select * from tab;
